- platform: darksky
  name: "Dark Sky Weather"
  api_key: !secret dark_sky_key
  scan_interval:
    minutes: 10
  monitored_conditions:
    - summary
    - hourly_summary
    - temperature
    - temperature_high
    - temperature_low

- platform: mqtt
  state_topic: dummy/floorplan/sensor
  name: dark_sky_weather_icon


