- alias: Turn off Downstairs Thermostat at 10:45
  trigger:
    - platform: time
      at: '21:45:00'
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
    - service: script.set_downstairs_thermostat
      data:
        heating_temp: '68'
        cooling_temp: '80'

- alias: Turn Downstairs Thermostat on at 06:00
  trigger:
    - platform: time
      at: '06:00:00'
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
    - service: script.set_downstairs_thermostat
      data:
        heating_temp: '72'
        cooling_temp: '78'

###########################
# Work around for iffy heat
- alias: Turn off Downstairs Thermostat at 6:05
  trigger:
    - platform: time
      at: '06:10:00'
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
    - service: script.set_downstairs_thermostat
      data:
        mode: 'off'
        heating_temp: '60'
        cooling_temp: '78'

- alias: Turn Downstairs Thermostat on at 06:10
  trigger:
    - platform: time
      at: '06:20:00'
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
    - service: script.set_downstairs_thermostat
      data:
        mode: 'heat_cool'
        heating_temp: '72'
        cooling_temp: '78'
############################

- alias: Turn Downstairs Heat Down when not home
  trigger:
    - platform: state 
      entity_id: group.household
      from: 'home'
      to: 'not_home'
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
    - service: script.set_downstairs_thermostat
      data:
        heating_temp: '67'
        cooling_temp: '80'

- alias: Turn Downstairs Heat Down when on Vacation
  trigger:
    - platform: state
      entity_id: input_boolean.vacation_mode
      from: 'off'
      to: 'on'
  action:
    - service: script.set_downstairs_thermostat
      data:
        heating_temp: '68'
        cooling_temp: '80'

- alias: Reset Downstairs Heat
  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'
  action:
    - service: script.set_downstairs_thermostat
      data:
        heating_temp: '72'
        cooling_temp: '78'


