- alias: Turn off Downstairs Thermostat at 10:45
  trigger:
    - platform: time
      at: '21:45:00'
  action:
    - service: climate.set_hvac_mode
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_mode
      data_template:
        hvac_mode: "heat_cool"
    - service: climate.set_temperature
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_mode
      data_template:
        target_temp_low: "70"
        target_temp_high: "95"

- alias: Turn Downstairs Thermostat on at 06:00
  trigger:
    - platform: time
      at: '06:00:00'
  action:
    - service: climate.set_hvac_mode
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_mode
      data_template:
        hvac_mode: "heat_cool"
    - service: climate.set_temperature
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_mode
      data_template:
        target_temp_low: "73"
        target_temp_high: "95"

###########################
# Work around for iffy heat
- alias: Turn off Downstairs Thermostat at 6:05
  trigger:
    - platform: time
      at: '06:05:00'
  action:
    - service: script.set_downstairs_thermostat
      data:
        mode: 'off'
        heating_temp: '60'
        cooling_temp: '95'

- alias: Turn Downstairs Thermostat on at 06:10
  trigger:
    - platform: time
      at: '06:10:00'
  action:
    - service: script.set_downstairs_thermostat
      data:
        mode: 'heat_cool'
        heating_temp: '72'
        cooling_temp: '95'

############################
#
#- alias: Turn Downstairs Heat Down when not home
#  trigger:
#    - platform: state 
#      entity_id: group.household
#      from: 'home'
#      to: 'not_home'
#  condition:
#    condition: state
#    entity_id: input_boolean.vacation_mode
#    state: 'off'
#  action:
#    - service: script.set_downstairs_thermostat
#      data:
#        heating_temp: '67'
#        cooling_temp: '80'
#
#- alias: Turn Downstairs Heat Down when on Vacation
#  trigger:
#    - platform: state
#      entity_id: input_boolean.vacation_mode
#      from: 'off'
#      to: 'on'
#  action:
#    - service: script.set_downstairs_thermostat
#      data:
#        heating_temp: '68'
#        cooling_temp: '80'
#
#- alias: Reset Downstairs Heat
#  trigger:
#    - platform: state
#      entity_id: group.household
#      from: 'not_home'
#      to: 'home'
#  action:
#    - service: script.set_downstairs_thermostat
#      data:
#        heating_temp: '72'
#        cooling_temp: '78'


